[package]
name = "sudoku"
version = "0.1.0"
authors = ["lemontrachet <johnny.ward@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.3"
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
permutohedron = "0.2.4"
